require:
  - rubocop-rails-accessibility

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'pkg/**/*'
    - '.bundle/**/*'
  TargetRubyVersion: 3.3

Lint/MissingSuper:
  Exclude:
    - "app/components/**/*.rb"

# https://rubocop.readthedocs.io/en/latest/cops_metrics/#metricsmethodlength
Metrics/MethodLength:
  CountComments: false
  Max: 15
